# permissions for admin users to manage agenttasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: agenttask-admin-role
rules:
- apiGroups:
  - agents.bulletfarm.io
  resources:
  - agenttasks
  verbs:
  - '*'
- apiGroups:
  - agents.bulletfarm.io
  resources:
  - agenttasks/status
  verbs:
  - get
